---

### docker ###

- name: Install OS requirements
  # https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#os-requirements
  apt: name=apt-transport-https,ca-certificates,curl,software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: "0EBFCD88"

- name: Set up docker's stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"

- name: Install docker-ce
  apt:
    name: docker-ce={{docker_version}}


### dokku ###

- name: Add packagecloud's official GPG key
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    id: "C2E73424D59097AB"

- name: Setup dokku's repository
  apt_repository:
    # http://dokku.viewdocs.io/dokku/getting-started/install/debian/
    repo: "deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main"

# http://dokku.viewdocs.io/dokku/getting-started/install/debian/#unattended-installation

- name: "debconf dokku/vhost_enable"
  debconf:
    name: dokku
    question: dokku/vhost_enable
    value: "{{ dokku_vhost_enable }}"
    vtype: boolean

- name: "debconf dokku/web_config"
  debconf:
    name: dokku
    question: dokku/web_config
    value: "{{ dokku_web_config }}"
    vtype: boolean

- name: "debconf dokku/hostname"
  debconf:
    name: dokku
    question: dokku/hostname
    value: "{{ dokku_hostname }}"
    vtype: string

- name: "debconf dokku/skip_key_file"
  debconf:
    name: dokku
    question: dokku/skip_key_file
    value: "{{ dokku_skip_key_file }}"
    vtype: boolean

- name: "debconf dokku/key_file"
  debconf:
    name: dokku
    question: dokku/key_file
    value: "{{ dokku_key_file }}"
    vtype: string

- name: Install dokku
  apt:
    name: dokku={{dokku_version}}
  ignore_errors: true

- name: Install core plugins
  shell: dokku plugin:install-dependencies --core


### setup dokku users with tequlia-common dev users ###

- name: Get current dokku users
  command: dokku ssh-keys:list
  changed_when: False
  register: dokku_ssh_users
  ignore_errors: true

- name: Add admin users to dokku
  shell: 'echo "{{ item.public_keys.0 }}" | dokku ssh-keys:add {{ item.name }}'
  when: dokku_ssh_users is defined and dokku_ssh_users.stdout.find(item.name) == -1
  with_items: "{{ users }}"


### clean up ###

- name: Hold docker and dokku versions
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - dokku

- name: Allow port 80 through firewall
  ufw: rule=allow port=http

- name: Allow port 443 through firewall
  ufw: rule=allow port=https

- name: Add dokku user to tequila-common groups
  user:
    name: dokku
    groups: admin,login
    append: yes
