# http://dokku.viewdocs.io/dokku/getting-started/upgrading/#upgrade-instructions
---

- name: Stop running dokku apps
  command: dokku --quiet apps:list | xargs -L1 dokku ps:stop
  tags: upgrade

- name: Unhold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - docker-ce
    - dokku
  tags: upgrade

- name: Install docker-ce
  apt:
    name: docker-ce={{docker_version}}
    update_cache: true
    force: true
  tags: upgrade

- name: Install dokku
  apt:
    name: dokku={{dokku_version}}
    update_cache: true
    force: true
  tags: upgrade

- name: Hold docker and dokku versions
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - docker-ce
    - dokku
  tags: upgrade

- name: Restart all dokku apps
  command: dokku ps:restartall
  tags: upgrade
